{{- if .Values.prometheusAgent.enabled }}
{{- if .Values.prometheusAgent.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheusAgent.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: prometheus-agent
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: observability
  {{- with .Values.prometheusAgent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
