apiVersion: v2
name: backend-service
description: Tekmetric Backend Service Helm Chart
type: application
version: 0.1.0
appVersion: "1.0-SNAPSHOT"

dependencies:
  - name: tekmetric-common-chart
    version: "0.1.3"
    repository: "s3://tekmetric-helm-charts-dev/charts"
