{{- /*
Tekmetric Common Chart - ServiceAccount Template
Kubernetes ServiceAccount resource configuration
*/ -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "tekmetric.fullname" .) }}
  namespace: {{ include "tekmetric.namespace" . }}
  labels:
    {{- include "tekmetric.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
